stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
    - pip install pytest pytest-flask
  script:
    - python -m pytest tests/ -v --tb=short
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Triggering Render deployment"
    - |
      if [ -n "$RENDER_DEPLOY_HOOK" ]; then
        curl -X POST "$RENDER_DEPLOY_HOOK"
        echo "Deployment triggered successfully"
      else
        echo "No deployment hook configured"
      fi
  only:
    - main
  when: manual
