### `render.yaml`
```yaml
services:
  - type: web
    name: data-analyst-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 2
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: tmp-disk
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /health
